AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Resources:
  DynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions: 
        - 
          AttributeName: "Title"
          AttributeType: "S"
        - 
          AttributeName: "ItemGUID"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "Title"
          KeyType: "HASH"
        - 
          AttributeName: "ItemGUID"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "Feed"
      StreamSpecification:
        StreamViewType: "NEW_IMAGE"
  DdbWriter:
    Type: "AWS::Serverless::Function"
    Properties:
     Runtime: go1.x
     Policies:
       - "AWSLambdaBasicExecutionRole"
       - Version: "2012-10-17"
         Statement:
           -
             Effect: "Allow"
             Action:
               - "dynamodb:UpdateItem"
             Resource:
               Fn::GetAtt:
                 - "DynamoDBTable"
                 - "Arn"
     Handler: "main"
     CodeUri: "cmd/ddb_writer/"
     Events:
       ScheduledRule1:
         Type: "Schedule"
         Properties:
           Schedule: "rate(2 minutes)"
           Input: "{\"url\":\"changeme\"}"
       ScheduledRule2:
         Type: "Schedule"
         Properties:
           Schedule: "rate(5 minutes)"
           Input: "{\"url\":\"changeme\"}"
     Environment:
       Variables:
         DDB_TABLE_NAME:
           Ref: "DynamoDBTable"
     Timeout: 60
     Tracing: "Active"
  DdbStreamReader:
    Type: "AWS::Serverless::Function"
    Properties:
     Runtime: go1.x
     Policies:
       - "AWSLambdaBasicExecutionRole"
       - "AWSLambdaInvocation-DynamoDB"
     Handler: "main"
     CodeUri: "cmd/ddb_stream_reader/"
     Events:
       DdbStreamEvent:
         Type: "DynamoDB"
         Properties:
           StartingPosition: "LATEST"
           Stream:
             Fn::GetAtt:
               - "DynamoDBTable"
               - "StreamArn"
     Timeout: 60
     Tracing: "Active"
